# fly.toml app configuration file generated for cat-rest on 2025-04-28T12:05:10-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cat-rest'
primary_region = 'den'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

# [env]
#BUCKET_ENDPOINT=$BUCKET_ENDPOINT
#AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
#AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
#API_USER=$API_USER
#API_PASS=$API_PASS
