name: Fly.io Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          flyctl secrets set -t $FLY_API_TOKEN BUCKET_ENDPOINT=${{ secrets.BUCKET_ENDPOINT }}
          flyctl secrets set -t $FLY_API_TOKEN AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          flyctl secrets set -t $FLY_API_TOKEN AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          flyctl secrets set -t $FLY_API_TOKEN API_USER=${{ secrets.API_USER }}
          flyctl secrets set -t $FLY_API_TOKEN API_PASS=${{ secrets.API_PASS }}
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
